changes in readme file for build on windows os
zynaddsubfx/zyn-fusion-build pull request #105
Opened 2023-03-24 21:39 UTC by marahmbawwab

2023-03-25 20:36 UTC, pgervais requested changes
Thanks for  the detailed instructions! There are a few minor issues with the Markdown formatting, which makes the text very hard to read once rendered. See my comments on the files.

2023-03-25 20:36 UTC, pgervais commented on README.md
> +-Download msys2 then open the shell and type those commands respectively:
For this list to render correctly, you need to add a space after each dash. Example:

```
- Download msys2 then ...
- Open msys2-mingw64 shell from ...
```

You can check the rendering of a markdown (.md) file on Github by clicking the three-dot menu on the right and choosing "view file".
```

2023-03-25 20:36 UTC, pgervais commented on README.md
> + update pacman -Syu then pacman -su.
Using backticks here will help the reader understand what exactly is to be run. See the difference:
Did you mean to run `update pacman -Syu` or `pacman -Syu`?

This was formatted by writing

```
Did you mean to run `update pacman -Syu` or `pacman -Syu`?
```

2023-03-25 20:36 UTC, pgervais commented on README.md
> + pacman mingw-w64-x86-toolchain
You can use this technique to make those three lines of code look nicer: https://www.markdownguide.org/basic-syntax/#code-blocks-1

(TL;DR: indent those lines with 8 spaces)

2023-03-27 12:00 UTC, pgervais commented on README.md
> +-  Continue the commands below:
`Continue with the commands below:`

2023-03-29 01:26 UTC, fundamental commented
Thanks for the documentation enhancement :+1:

2023-03-29 01:26 UTC, merged